GET http://localhost:8001/ddclient/randomstring
X-B3-client: 1
X-B3-account: 1a

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
Baggage-bclient: 1
Baggage-baccount: 1a
ot-baggage-baccount: 1a
ot-baggage-bclient: 1
tracestate: bclient=1,baccount=1a

<> 2023-02-08T010428.200.txt

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
Baggage-bclient: 1
Baggage-baccount: 1a
ot-baggage-baccount: 1a
ot-baggage-bclient: 1
tracestate: bclient=1,baccount=1a

<> 2023-02-08T010417.200.txt

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
Baggage-bclient: 1
Baggage-baccount: 1a
ot-baggage-baccount: 1a
ot-baggage-bclient: 1
tracestate: bclient=1,baccount=1a

<> 2023-02-08T010313.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
Baggage-bclient: 1
Baggage-baccount: 1a
ot-baggage-baccount: 1a
ot-baggage-bclient: 1
tracestate: bclient=1,baccount=1a

<> 2023-02-08T010231.200.txt

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
Baggage-bclient: 1
Baggage-baccount: 1a
ot-baggage-baccount: 1a
ot-baggage-bclient1:

<> 2023-02-08T004049.200.txt

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
Baggage-bclient: 1
Baggage-baccount: 1a

<> 2023-02-08T003705.200.txt

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
Baggage-bclient: 1
Baggage-baccount: 1a

<> 2023-02-08T003552.200.txt

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
baggage-bclient: 1
baggage-baccount: 1a

<> 2023-02-08T003424.200.txt

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
baggage-bclient: 1,
baggage-baccount: 1a

<> 2023-02-08T003235.200.txt

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T235851.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 2
x-account: 2a
X-B3-client: 2
X-B3-account: 2a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1,baccount=1a

<> 2023-02-07T235848.200.txt

###

GET http://localhost:9001/otlpclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a

###

GET http://localhost:9001/otlpclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T235750.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T235741.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T235619.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T235617.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T235613.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T235601.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T235438.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T235430.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T235300.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 2
x-account: 2a
X-B3-client: 2
X-B3-account: 2a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1,baccount=1a

<> 2023-02-07T235125.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 2
x-account: 2a
X-B3-client: 2
X-B3-account: 2a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1,baccount=1a

<> 2023-02-07T234748.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 2
x-account: 2a
X-B3-client: 2
X-B3-account: 2a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1,baccount=1a

<> 2023-02-07T234727.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 2
x-account: 2a
x-b3-client: 2
x-b3-account: 2a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1,baccount=1a

<> 2023-02-07T234616.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T234549.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 2
x-account: 2a
x-b3-client: 2
x-b3-account: 2a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1,baccount=1a

<> 2023-02-07T234339.200.txt

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T232032.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T231649.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1,baccount=1a

<> 2023-02-07T231322.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1,baccount=1a

<> 2023-02-07T231211.200.txt

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1,baccount=1a

<> 2023-02-07T231209.200.txt

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T231050.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T231025.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T231011.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1,baccount=1a

<> 2023-02-07T231005.200.txt

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T225840.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T225801.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T225732.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1,baccount=1a

<> 2023-02-07T225650.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
X-B3-client: 1
X-B3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1,baccount=1a

<> 2023-02-07T225530.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T225500.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
x-datadog-client: 3
x-datadog-account: 3a
baggage: bclient=3,baccount=3a

<> 2023-02-07T225418.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
X-B3-client: 1
X-B3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1
baggage: baccount-1a

<> 2023-02-07T225049.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
X-B3-client: 1
X-B3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1

<> 2023-02-07T224003.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
x-datadog-client: 1
x-datadog-account: 1a
baggage: bclient=1

<> 2023-02-07T223749.500.json

###

GET http://localhost:8001/ddclient/randomstring
x-client: 1
x-account: 1a
x-b3-client: 1
x-b3-account: 1a
dd-client: 1
dd-account: 1a
baggage: bclient=1,baccount=1a

<> 2023-02-07T223634.500.json

###

GET http://localhost:8001/ddclient/randomstringfailure
x-client: 3
x-account: 3a
x-b3-client: 3
x-b3-account: 3a
baggage: bclient=1,baccount=1a

<> 2023-02-07T222841.500.json

###

